openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of my Contacts app
tags:
  - name: Contacts
    description: Operations about create users, delete users, update users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    put:
      $ref: '../swagger/paths/contacts/{id}/put.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /google-auth-url:
    get:
      $ref: '../swagger/paths/auth/google-auth-url.yaml'
  /confirm-google:
    post:
      $ref: '../swagger/paths/auth/confirm-google.yaml'
  /send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
